### ISSUE TITLE
Add more meta description of monitor

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/kryptokrona-api#103]
When for example pasting the link to the monitor: `https://stage.xkr.mjovanc.com/monitor` make sure to include a picture of the Kryptokrona API located in resources in the repo. As well as additional information about the service. Currently we get:

<img width="441" alt="Skärmavbild 2023-04-10 kl  19 49 29" src="https://user-images.githubusercontent.com/33717111/230960826-a0a25264-c6eb-4734-9dd1-971727ce702d.png">

**Comment by mjovanc** [comment]
@appelskrutt34 This is done now right? Have it been tested?

**Comment by appelskrutt34** [comment]
@mjovanc Yes this one is done and tested. You can test it also here: https://metatags.io/

**Comment by mjovanc** [comment]
@appelskrutt34 Ok, fix the width/height property and we can close this later :)
