### ISSUE TITLE
Make search bar in monitor to dark mode

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/kryptokrona-api#104]
Currently on dark mode it's white and it would probably look better with dark grey or black in some places.

**Comment by appelskrutt34** [comment]
@mjovanc hmmm im not fully convinced about this, I think it looks better with a white input field, it matches the white borders of the table (:

**Comment by mjovanc** [comment]
I was thinking of how GitHub is when its dark mode. Like this:

<img width="873" alt="Skärmavbild 2023-04-11 kl  15 42 46" src="https://user-images.githubusercontent.com/33717111/231182227-db854fd2-6b73-465f-bff7-bda40bcb0c4f.png">

But I'm all ears if you insist we keep it like we have it now. :)

**Comment by appelskrutt34** [comment]
@mjovanc ok i will try see how it looks

**Comment by mjovanc** [comment]
We removed the search bar to use pagination instead. Closing issue.
